# Generated by Django 3.1.3 on 2020-12-10 11:12

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
            ],
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('tv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_Of_collection', models.DateField(default=django.utils.timezone.now)),
                ('plate_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
                ('permit', models.CharField(choices=[('ALL INDIA PERMIT', 'ALL INDIA PERMIT'), ('STATE PERMIT', 'STATE PERMIT'), ('CITY', 'CITY')], max_length=20)),
                ('pincode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
            ],
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('area', models.CharField(max_length=150)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcesssingPlant',
            fields=[
                ('organisationaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='invt.organisationaddress')),
                ('pp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ppname', models.CharField(max_length=100)),
                ('total_waste', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
                ('landfill_waste', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
            ],
            bases=('invt.organisationaddress',),
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('waste_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_waste', models.CharField(choices=[('Recyable', 'Recyable'), ('Non-Recyable', 'Non-Recyable')], max_length=20)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
                ('tpuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invt.tuser')),
                ('tv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invt.transportvehicle')),
            ],
        ),
        migrations.AddField(
            model_name='transportvehicle',
            name='pp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invt.processsingplant'),
        ),
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('organisationaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='invt.organisationaddress')),
                ('lf_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lfname', models.CharField(max_length=100)),
                ('maximum_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
                ('capacity_filled', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
                ('pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invt.processsingplant')),
            ],
            bases=('invt.organisationaddress',),
        ),
    ]
