# Generated by Django 3.1.3 on 2020-12-25 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invt', '0003_auto_20201225_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppname', models.CharField(max_length=20)),
                ('date_collection', models.DateField(default=django.utils.timezone.now)),
                ('waste_qty', models.IntegerField()),
            ],
        ),
    ]
