# Generated by Django 3.1.3 on 2020-12-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invt', '0004_wasteml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteml',
            old_name='date_collection',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='wasteml',
            name='ppname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invt.processsingplant'),
        ),
    ]
